### ISSUE TITLE
Trouble installing Validator-Keys-Tool

### ISSUE THREAD

**Issue by Brietoe** [ripple/validator-keys-tool#10]
Hello,

I'm trying to host my own Rippled Validator and as a part of the process, I need to generate a key using the 'Validator-Keys-Tool.' 

I've been stuck on a particular step in the process and though I would ask to see if you had any insight into the issue. I'm sure I will eventually figure it out but if it's something anyone is familiar with, any assistance would be appreciated.

Following the README for this project, I cloned the repository, "CD'ed" into the directory and executed in bash: "cmake -DCMAKE_BUILD_TYPE=Release ../.."

That's where I get stuck. Here's a log of the situation:
_```
brietoe@Brownie-PC:~/validator-keys-tool/build/gcc.debug$ export BOOST_LIBRARYDIR=/home/brietoe/validator-keys-tool/build/gcc.debug/boost_1_68_0/libs
brietoe@Brownie-PC:~/validator-keys-tool/build/gcc.debug$ export BOOST_ROOT=/home/brietoe/validator-keys-tool/build/gcc.debug/boost_1_68_0/
brietoe@Brownie-PC:~/validator-keys-tool/build/gcc.debug$ cmake -DCMAKE_BUILD_TYPE=Release ../..
-- Installed rippled not found...using local FC
-- Pausing to download rippled source...
-- rippled version: 1.2.4
-- NIH-EP cache path: /home/brietoe/validator-keys-tool/.nih_c/unix_makefiles/GNU_7.4.0/Release
-- BOOST_ROOT: /home/brietoe/validator-keys-tool/build/gcc.debug/boost_1_68_0
-- BOOST_LIBRARYDIR:
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   chrono
--   context
--   coroutine
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
--   atomic
-- Pausing to download NuDB...
[ 11%] Performing download step (git clone) for 'nudb_src-populate'
Cloning into 'nudb_src-src'...
Note: checking out '1.0.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at da09745 Set version to 1.0.0
Submodule 'doc/docca' (https://github.com/vinniefalco/docca.git) registered for path 'doc/docca'
Submodule 'extras/beast' (https://github.com/vinniefalco/Beast.git) registered for path 'extras/beast'
Submodule 'extras/rocksdb' (https://github.com/facebook/rocksdb.git) registered for path 'extras/rocksdb'
Cloning into '/home/brietoe/validator-keys-tool/.nih_c/unix_makefiles/GNU_7.4.0/Release/nudb_src-src/doc/docca'...
Cloning into '/home/brietoe/validator-keys-tool/.nih_c/unix_makefiles/GNU_7.4.0/Release/nudb_src-src/extras/beast'...
Cloning into '/home/brietoe/validator-keys-tool/.nih_c/unix_makefiles/GNU_7.4.0/Release/nudb_src-src/extras/rocksdb'...
Submodule path 'doc/docca': checked out '335dbf9c3613e997ed56d540cc8c5ff2e28cab2d'
**error: Server does not allow request for unadvertised object** 2f9a8440c2432d8a196571d6300404cb76314125
Fetched in submodule path 'extras/beast', but it did not contain 2f9a8440c2432d8a196571d6300404cb76314125. Direct fetching of that commit failed.
**CMake Error at nudb_src-subbuild/nudb_src-populate-prefix/tmp/nudb_src-populate-gitclone.cmake:93 (message):
  Failed to update submodules in:
  '/home/brietoe/validator-keys-tool/.nih_c/unix_makefiles/GNU_7.4.0/Release/nudb_src-src'**

CMakeFiles/nudb_src-populate.dir/build.make:90: recipe for target 'nudb_src-populate-prefix/src/nudb_src-populate-stamp/nudb_src-populate-download' failed
make[2]: *** [nudb_src-populate-prefix/src/nudb_src-populate-stamp/nudb_src-populate-download] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/nudb_src-populate.dir/all' failed
make[1]: *** [CMakeFiles/nudb_src-populate.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

CMake Error at /usr/local/share/cmake-3.12/Modules/FetchContent.cmake:798 (message):
  Build step for nudb_src failed: 2
Call Stack (most recent call first):
  /usr/local/share/cmake-3.12/Modules/FetchContent.cmake:889 (__FetchContent_directPopulate)
  .nih_c/unix_makefiles/GNU_7.4.0/Release/rippled_src-src/CMakeLists.txt:1161 (FetchContent_Populate)

-- Configuring incomplete, errors occurred!
See also "/home/brietoe/validator-keys-tool/build/gcc.debug/CMakeFiles/CMakeOutput.log".
See also "/home/brietoe/validator-keys-tool/build/gcc.debug/CMakeFiles/CMakeError.log".
brietoe@Brownie-PC:~/validator-keys-tool/build/gcc.debug$
```_

Any assistance is appreciated. Thank you!

**Comment by mellery451** [comment]
It looks like one of the secondary dependencies moved its github location and it seems like the submodule links don't always follow redirects. The simplest fix it to update to the latest release of rippled/xrpl_core, so I have done that in `master`. Unfortunately that also brings a boost 1.70 requirement, so you will have to rebuild boost as well (sorry!)

If you prefer not to hassle with building this from source, we do provide a compiled `validator_keys_tool` in the `rippled` rpm and deb packages (https://xrpl.org/install-rippled.html) - not sure if one of those would work for you.

**Comment by derekneves** [comment]
Running into a simliar issue trying to build the validator_keys_tool, is the compiled binary still included in .deb and .rpm packages ? Ive tried installing via repos and it just has the node/daemon and no validator_keys_tool binary , help!

**Comment by ximinez** [comment]
The binary will be named `validator-keys`.

**Comment by derekneves** [comment]
Ed thanks for the reply

root@e1c6a01ecda2:/# apt -y update &&  apt -y install rippled
Hit:1 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:3 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Get:4 https://repos.ripple.com/repos/rippled-deb noble InRelease [23.6 kB]
Hit:5 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Get:6 https://repos.ripple.com/repos/rippled-deb noble/stable amd64 Packages [2069 B]
Fetched 25.6 kB in 3s (8304 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  rippled
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 19.1 MB of archives.
After this operation, 77.9 MB of additional disk space will be used.
Get:1 https://repos.ripple.com/repos/rippled-deb noble/stable amd64 rippled amd64 2.2.3-1 [19.1 MB]
Fetched 19.1 MB in 2s (11.4 MB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package rippled.
(Reading database ... 8704 files and directories currently installed.)
Preparing to unpack .../rippled_2.2.3-1_amd64.deb ...
Unpacking rippled (2.2.3-1) ...
Setting up rippled (2.2.3-1) ...
root@e1c6a01ecda2:/#
root@e1c6a01ecda2:/#

root@e1c6a01ecda2:/# ls -lah /opt/ripple/
total 16K
drwxr-xr-x 4 rippled rippled 4.0K Oct 31 09:20 .
drwxr-xr-x 1 root    root    4.0K Oct 31 09:20 ..
drwxr-xr-x 2 rippled rippled 4.0K Oct 31 09:20 bin
drwxr-xr-x 2 rippled rippled 4.0K Oct 31 09:20 etc
root@e1c6a01ecda2:/# ls -lah /opt/ripple/etc/
total 80K
drwxr-xr-x 2 rippled rippled 4.0K Oct 31 09:20 .
drwxr-xr-x 4 rippled rippled 4.0K Oct 31 09:20 ..
-rw-r--r-- 1 rippled rippled  63K Sep 14 16:21 rippled.cfg
-rw-r--r-- 1 root    rippled  355 Sep 15 11:30 update-rippled-cron
-rw-r--r-- 1 rippled rippled 2.3K Sep 14 16:21 validators.txt

root@e1c6a01ecda2:/# ls -lah /opt/ripple/bin/
total 75M
drwxr-xr-x 2 rippled rippled 4.0K Oct 31 09:20 .
drwxr-xr-x 4 rippled rippled 4.0K Oct 31 09:20 ..
-rwxr-xr-x 1 rippled rippled 4.6K Sep 15 11:30 getRippledInfo
-rwxr-xr-x 1 rippled rippled  75M Sep 15 11:30 rippled
-rwxr-xr-x 1 rippled rippled 1.8K Sep 15 11:30 update-rippled.sh
root@e1c6a01ecda2:/#


root@e1c6a01ecda2:/# dpkg -L rippled | grep /bin/
/opt/ripple/bin/getRippledInfo
/opt/ripple/bin/rippled
/opt/ripple/bin/update-rippled.sh
/usr/local/bin/rippled


Do i need to specify a specific version of rippled package ?
